### ISSUE TITLE
Compiling nightmare

### ISSUE THREAD

**Issue by crapgeek** [namreeb/nampower#1]
After trying to update the references to boost and hadesmem i still cant find the itab.h... Such a waist of time!
So, in order to run this #$#, i have to install boost (8GB, if i hadn't installed it already) and the shitty hadesmem?

No, thanks.

I'll rather try some other simpler solution.

**Comment by namreeb** [comment]
It's not complicated to setup.  But if you can't manage to do that, you could download the binary release that is on this repository.  Let me know if you can't manage to do that either.

If no option meets with your approval, I invite you to request a full refund through our customer service department.
