### ISSUE TITLE
Please build release of v2

### ISSUE THREAD

**Issue by WiNiFiX** [namreeb/nampower#11]
... since not all references are included in source like hadesmem, and the github that hosted it is no longer existent.

**Comment by namreeb** [comment]
I am getting close.  In the mean time, you can find hadesmem [here](https://bitbucket.org/raptorfactor/hadesmem) if you want to try it yourself.  Also, if you are willing to commit to reporting reproducible bugs back to me, I can provide you with a binary of the current version.  You might call it a 2.0 alpha.

**Comment by WiNiFiX** [comment]
Oh thanks for the link, that's all I will need, will build it.
Your commit comments made it sound like v2 was done and dusted, you had just not built a release, whats still outstanding, so I am aware of the limitations in advance.

**Comment by namreeb** [comment]
Yeah, sorry about that.  Whenever I think I have it working 100% I discover some new problem.  I currently have no known issues, but nor have I used it enough to feel secure about that.

**Comment by namreeb** [comment]
Actually that is not quite true.  There are some issues, but none that I feel are important enough to merit delaying a binary release of 2.0.

**Comment by namreeb** [comment]
In case you're interested, hadesmem has been rehosted (with permission from the author) here: https://github.com/namreeb/hadesmem -- complete with an action and artifacts.
