### ISSUE TITLE
2.0 - Casting gets "stuck"

### ISSUE THREAD

**Issue by Neejrow** [namreeb/nampower#12]
I have noticed with 2.0 that sometimes when casting, the cast bar will get stuck on and you will not actually cast anything. I have to then cast a different spell to remove the stuck cast bar and allow me to cast again.

Very easy to reproduce when queueing up mass crafting. The crafting process will halt because the cast bar gets stuck on and it cannot continue.

**Comment by namreeb** [comment]
Yeah I have seen that happen sometimes too.  I'm not entirely sure what is causing it.  Good tip on the crafting to reproduce it, though.

**Comment by namreeb** [comment]
Can you please try release [2.1](https://github.com/namreeb/nampower/tree/2.1) and let me know if there is any improvement?
