### ISSUE TITLE
2.0 - Cancelled Casts on LH

### ISSUE THREAD

**Issue by Sunpadow** [namreeb/nampower#13]
With version 2.0 while spam casting on a Light's Hope server I will occasionally get an error message and a spellcast that does nothing. The UI error message is usually "Another action is in progress", and rarely "Spell is not ready yet" (with a spammable spell). When the error shows up the next cast will appear to be cancelled (castbar disappears) but i'm unable to start another cast until it finishes or I move to cancel it manually. If I let it finish on its own the cast takes no mana and does no damage or healing. 

Unlike the other issue brought up by Neejrow I don't have to cast a different spell to "unstick" it. The next cast of the same spell will work normally and it only gets "stuck" for as long as the cast was supposed to take.

This is only on Light's Hope (both Northdale and Lightbringer). Version 2.0 appeared to work flawlessly on Kronos. I have no issues like this with the older version of nampower on Light's Hope. Checked without addons, same WoW client.

**Comment by HelloKitty** [comment]
Same

**Comment by namreeb** [comment]
Can you please try release [2.1](https://github.com/namreeb/nampower/tree/2.1) and let me know if there is any improvement?

**Comment by Sunpadow** [comment]
Thank you namreeb, version 2.1.7 appears to completely fix this issue. In an hour of testing I haven't been able to replicate this issue while using this new version.

I can still replicate this issue with version 2.0 so it is unlikely that anything has been done about it server-side.

**Comment by namreeb** [comment]
Thanks for letting me know.
