### ISSUE TITLE
Breaks HealComm

### ISSUE THREAD

**Issue by raethkcj** [namreeb/nampower#14]
HealComm (https://github.com/Aviana/HealComm) is an addon used to show predictive healing amounts on unit frames. It's included in Luna and several other unit frames addons, and is available for base raid frames as well. I'm using the version included with Luna, but after installing the nampower 2.0 binary, I'm unable to see predictive heals that I cast. I can still see the predictive heals that other members of my party/raid cast. I'm not sure if anything can be done, but it seems that nampower is somehow preventing HealComm from detecting a heal cast.

**Comment by namreeb** [comment]
Can you please try release [2.1](https://github.com/namreeb/nampower/tree/2.1) and let me know if there is any improvement?
