### ISSUE TITLE
Profession bug - item complete, and it gets stuck. 

### ISSUE THREAD

**Issue by Mistymimi** [namreeb/nampower#20]
Some background: I was creating multiple heavy linen bandages on darrowshire. I have between 130 and 150 ping usually. I've encountered this about a dozen times and only seem to encounter it while using nampower. I don't recall it happening with hundreds of other items i've created with profressions on vanilla servers in the past: darrowshire included. I believe darrowshire uses Vmangos, though I know it is modified in some ways, but to my knowledge shouldn't be modified in any ways that affects profressions.

**Comment by namreeb** [comment]
So you're using the professions pane in the UI, you tell it to make a bunch of linen bandages, and somewhere in the middle the cast bar gets stuck?

**Comment by Mistymimi** [comment]
Correct, the cast bar gets stuck displaying the item being fully complete but it doesn't ever give the item while casting this fully complete stuck cast of bandage creation. It only seems to happen when using nampower. I created about 60 more bandages without numpower, and couldn't recreate the issue while numpower is not in use. For reference with numpower it usually would get stuck between the 3rd and 8th bandage created while using multiple item craft.

**Comment by Mistymimi** [comment]
Something I didn't write, is that I suspect something is going wrong before the bar is filled, and the bar filling and not completing is just the side effect of it going wrong, rather than going wrong at the end of the craft.

**Comment by Mistymimi** [comment]
I noticed this same issue appears to have existed a few years ago as seen here: https://github.com/namreeb/nampower/issues/12

**Comment by Mistymimi** [comment]
I had a random thought, I wonder if spell batch settings a server has effects how often this bug occurs, apparently everlook will have minimal batching, if batching does indeed play a role in this, we may see this happen less often on everlook compaed to other servers.

**Comment by Mosch0512** [comment]
I got the exact same problem but for me it happens all the time after the first craft is completed it gets stuck.

**Comment by namreeb** [comment]
I believe this should be fixed by the contribution from @jimmytaker.  I'm currently trying to update the CI to build the releases so I don't have to.  So keep an eye out for the next release.
