### ISSUE TITLE
Auto shot macro not working on EVERLOOK/working on Kronos

### ISSUE THREAD

**Issue by GasperMilitello90** [namreeb/nampower#21]
Using a standard macro from nost that looks like this:

/script if GetUnitName("target")==nil then TargetNearestEnemy() end
/run if CheckInteractDistance("target", 3) and (not PlayerFrame.inCombat) then AttackTarget() elseif not IsAutoRepeatAction(3) then CastSpellByName("Auto Shot") end

Macro works perfect with Nampower on the private server Kronos. However, on Everlook using the macro won't initiate the second part of the macro (unless pressed twice). I have tried everything possible, switching positions for the macro, disable all addons etc. It has to be something with Everlook's server - not sure what they are doing because I am not programming savvy. Thanks for your help and great addition to the vanilla community.

**Comment by namreeb** [comment]
I suspect that this is fixed by the 2.2 release, which can be found here: https://github.com/namreeb/nampower/releases.  If not, please feel free to re-open.
