### ISSUE TITLE
I can't see my spell motion

### ISSUE THREAD

**Issue by vanzibo** [namreeb/nampower#22]
When I use this software, it is really reduce my spell lag to zero, although the ping still show 300+, but some of my spell cast have no motion showing on my screen, another player around me can see my spell cast motion, but I can't, not as usual, could you please explain and fix it? Thank you.

**Comment by kotisorion** [comment]
I see same thing. Casting animations don't work. Great program otherwise. huge boost to performance for the high ping crowd. ty

**Comment by Mosch0512** [comment]
i wanted to check it out in your code haha but my coding skills arnt good enough haha if this is fixed this mod would be insane xD

**Comment by Mosch0512** [comment]
https://github.com/namreeb/nampower/pull/24 

This fixes it but it is not merged yet

**Comment by namreeb** [comment]
This should be fixed now.  Please re-open if not.
