### ISSUE TITLE
Possible to make it use trinket spells?

### ISSUE THREAD

**Issue by Sabre142** [namreeb/nampower#3]
This is a fantastic tool, I am wondering if it could be made to work also with trinket usage (i.e. Talisman of Ephemeral Power)?

I have sent this to you on reddit also

**Comment by namreeb** [comment]
That is an item use, not a spell cast. Not sure what you want to accomplish with this. Can you elaborate a little?

**Comment by Sabre142** [comment]
Trinket usage is delayed by ping (e.g. it takes .150 seconds for my trinket to activate after pressing the keybind)

I was wondering if there is someway to counter this to reduce it to (effectively) 0 seconds delay like regular spells when spammed nearing the end of a cast.

**Comment by Sabre142** [comment]
For now, I've managed to interweave the trinket with my frostbolts using the following macro:

/use Talisman of Ephemeral Power
/script SpellStopCasting()
/script CastSpellAtTarget(10181)
/script SpellStopCasting()

It requires some mashing but otherwise it works. The only real issue is that the castbar disappears, which could probably be remedied by an addon.

**Comment by namreeb** [comment]
This code doesn't bypass latency, per se.  It merely mitigates the impact of it when casting spells.  Since you're not using that trinket every few seconds, it wouldn't really help to take what's done for spells and apply it to the item.
