### ISSUE TITLE
Caution: Possible Warden Auto-Ban

### ISSUE THREAD

**Issue by Johnmichael** [namreeb/nampower#5]
Just a heads up to anyone using this, make sure you macros are 100% correct before ever using them. Double/triple/quadruple check your spell IDs, make sure your character knows the spell.  Check to see if your character unlearns the previous rank upon learning the latest rank. A friend of mine was using this on a rogue, and when he learned Sinister Strike rank 2, he was auto banned after pressing the macro. Thankfully he was just testing if there was any benefit for using this on melee, so it was a dummy account -- but still, realize what you're using.

For instance if you miss type a spellID, and press the macro -- Warden will see this as an attempt to cast a spell not available to your character, like you are trying to hack. This is an instant and permanent ban on most pservers.

This is a problem server side, but it's very difficult to be get unbanned if it was by Warden. Server staff may not know of this tool, and may not even investigate or help you just because it triggered the anti-hack. Beyond that, it looks suspicious for perma-banned accounts to become unbanned. It was meant to be permanent after all, not temporary.

Nampower is a great fix, but please use responsibly.

**Comment by namreeb** [comment]
The only server I know of that is this anal-retentive is Kronos. I've asked them to make it more lenient. There's no reason not to simply kick the player. But my request has gone ignored.

**Comment by Johnmichaelparsons** [comment]
Well. Thanks for contacting them on that. It's a shame they won't do anything.

**Comment by namreeb** [comment]
@Johnmichaelparsons what server was this on?

**Comment by Johnmichaelparsons** [comment]
kronos
