### ISSUE TITLE
How can I use the mouseover macro with luna unit frames?

### ISSUE THREAD

**Issue by cbook72** [namreeb/nampower#8]
When I use /script CastSpellAtMouseover(x) I am able to cast it on players within the game world as they're running about, however I cannot get this to interact with any raid frames. I've tried Luna/NotGrid/sRaidframes with zero luck. Has anyone found a work around?

**Comment by namreeb** [comment]
This is something I am aware of, but probably won't fix by itself.  I do have some code written for a nampower 2.0 which would change the way the stop-casting is achieved in such a way that this bug no longer happens (in that no macro is needed and all casts benefit from the speed-up).
