### ISSUE TITLE
Nampower not launching/questionable information

### ISSUE THREAD

**Issue by USERNAMETAKENN** [namreeb/nampower#9]
Current version of nampower says in the readme to run loader.exe but under the loader folder it does not have loader.exe in the actual folder to actually launch it.

So my friend gave me nampower1.2.7z. However when I attempted to launch it from the root WoW directory it produced dll errors. I googled the missing DLL errors and suggestions ranged from update your Visual Studio to find those dll's specifically and download them. 

I opted in to update my Visual studio, i grabbed 2010, 2015 and 2017 and none of them would work after installation and kept returning the same errors so I went to download the dll's manually (questionable functionality depending on version - I know) and after the DLL errors went away it just failed to launch.

Any clarification as to the potential fix you have for this would be appreciated. I am running Windows10 if that specific architecture affects your solution. Thanks!

**Comment by namreeb** [comment]
My guess is that you downloaded the source instead of the binary.  You have two choices.  You can compile it yourself, which will give you loader.exe, or you can download the binary from the releases section.  That can be found here: https://github.com/namreeb/nampower/releases

I believe that I compiled this with Visual Studio 2015.  If that is the case, you will need to have the Visual Studio 2015 redistributable package installed on your machine.  It can be downloaded here: https://www.microsoft.com/en-us/download/details.aspx?id=48145.

**Comment by USERNAMETAKENN** [comment]
For the first option: I did download Visual studio 2015 originally then upgraded to 2017 thinking it would retain the functionality of 2015. 2015 installer doesn't offer a rollback, and I admit I'm having an issue finding the application to run visual studio to compile it in 2017(not showing under programs and search function gives no executables when I search for "Visual" which is blowing my mind (could be part of the problem). So I did try the second option already with nampower1.2.7z  but it returns the .dll issues when ran in the root directory of WoW which I previously referred to.

Should I uninstall VS and install the 2015 version and try again? Any hints?

**Comment by USERNAMETAKENN** [comment]
I just have been just the redistribute packages not visual studio itself - thought it would be enough. I can't seem to get past this reoccuring .dll issue. I'm noticing Visual studio itself is a effin' huge download - but I'm installing it now to attempt to compile it myself. 

Hopefully compiling it manually returns favorable outcomes.

**Comment by namreeb** [comment]
If you're not familiar with C++ or compiling applications in Visual Studio, I would encourage you not to attempt it for this.  There is no reason to.  You'll likely end up having the same problem(s) with those binaries that you do with the ones in the releases section of this repository.

The simplest way to get nampower to launch is to take `nampower.dll` and `loader.exe`, copy them into your wow folder, and double click on `loader.exe`.
